---
    - name: add more node proccess to current reading clients
      hosts: "writing_clients"
      remote_user: benchUser
      become: yes
      tasks:
        - name: Check primary url
          ansible.builtin.debug:
            msg: "{{  hostvars[groups.writing_clients[0]].primary_copy }}"
        
        - name: Start first writing client to primary
          shell: cd ./CSBench/writingClient && pm2 start -f app.js -- "{{  hostvars[groups.writing_clients[0]].primary_copy }}"
        
        - name: Start second writing client to primary
          shell: cd ./CSBench/writingClient && pm2 start -f app.js -- "{{  hostvars[groups.writing_clients[0]].primary_copy }}"