---
    - name: Add client
      hosts: "writing_clients"
      remote_user: benchUser
      become: yes
      tasks:
        - name: update
          command: sudo apt -y update

        - name: install git
          command: sudo apt install git -y
        
        - name: install curl
          command: sudo apt install curl -y

        - name: install node
          shell: curl -sL https://deb.nodesource.com/setup_14.x | bash

        - name: install curl
          command: sudo apt install nodejs -y

        - name: clone repo
          shell: git clone https://github.com/klinkert0728/CSBench.git

        - name: Install dependencies
          shell: cd CSBench/writingClient && npm install && npm install pm2 -g
        
        - name: Start first writing client to primary
          ansible.builtin.shell: cd ./CSBench/writingClient && pm2 start -f app.js -- "{{  hostvars[groups.writing_clients[0]].primary_copy }}"
          loop:
            - 1
            - 2
            - 3
            - 4
            - 5