-
    #35.195.32.75  ansible_connection=ssh
    [writing_clients]
    {{#IPS}}
    {{.}} ansible_connection=ssh
    {{/IPS}}
    
    [reading_clients]
    {{READING_CLIENT}} ansible_connection=ssh
    
    [reading_clients:vars]
    ansible_user=benchUser
    ansible_ssh_private_key_file=./bench_dk_id_rsa
  
    
    [writing_clients:vars]
    ansible_user=benchUser
    ansible_ssh_private_key_file=./bench_dk_id_rsa