-
    #35.195.32.75  ansible_connection=ssh
    [db_replicas]
    {{#IPS}}
    {{.}} ansible_connection=ssh
    {{/IPS}}
    
    [primary_copy]
    {{PRIMARY}} ansible_connection=ssh
    
    [primary_copy:vars]
    ansible_user=benchUser
    ansible_ssh_private_key_file=./bench_dk_id_rsa
    
    [db_replicas:vars]
    ansible_user=benchUser
    ansible_ssh_private_key_file=./bench_dk_id_rsa